const overviewSections = [
  { key: "school", title: "School", dot: "gold", icon: "?" },
  { key: "work", title: "Werk", dot: "blue", icon: "?" },
  { key: "health", title: "Sport / gezondheid", dot: "mint", icon: "?" },
  { key: "stuff", title: "Spullen", dot: "gold", icon: "?" },
  { key: "appointments", title: "Afspraken", dot: "blue", icon: "?" },
  { key: "tasks", title: "Losse taken", dot: "mint", icon: "?" },
  { key: "ideas", title: "Idee?n", dot: "lavender", icon: "?" },
  { key: "projects", title: "Projecten", dot: "blue", icon: "?" },
  { key: "goals", title: "Doelen", dot: "gold", icon: "?" },
  { key: "worries", title: "Zorgen", dot: "rose", icon: "?" },
  { key: "routines", title: "Routines", dot: "blue", icon: "?" },
  { key: "social", title: "Sociaal", dot: "lavender", icon: "?" },
];

const categoryRules = {
  projects: [
    "project",
    "scriptie",
    "presentatie",
    "website",
    "portfolio",
    "campagne",
    "opleiding",
    "verbouwing",
    "verhuizen",
    "planning voor",
    "traject",
    "aanvraag",
  ],
  tasks: [
    "ik moet",
    "moet",
    "nog",
    "mail",
    "bel",
    "stuur",
    "maak",
    "regel",
    "koop",
    "boodschap",
    "boodschappen",
    "betaal",
    "plan",
    "boek",
    "check",
    "schrijf",
    "afronden",
    "afmaken",
    "opruimen",
    "voorbereiden",
    "uitzoeken",
    "inleveren",
    "betalen",
  ],
  goals: [
    "wil",
    "doel",
    "leren",
    "beter worden",
    "opbouwen",
    "gezonder",
    "meer rust",
    "minder",
    "sparen",
    "groeien",
    "richting",
    "toekomst",
  ],
  worries: [
    "zorg",
    "zorgen",
    "bang",
    "stress",
    "druk",
    "twijfel",
    "onzeker",
    "overweldigd",
    "te veel",
    "vergeten",
    "spannend",
    "geen tijd",
    "loopt achter",
  ],
  ideas: [
    "idee",
    "misschien",
    "ooit",
    "zou kunnen",
    "concept",
    "experiment",
    "probeer",
    "lijkt me",
    "brainstorm",
    "inspiratie",
    "trading",
  ],
  routines: [
    "elke dag",
    "dagelijks",
    "wekelijks",
    "routine",
    "gewoonte",
    "ochtend",
    "avond",
    "sporten",
    "wandelen",
    "slapen",
    "gezond eten",
    "mediteren",
  ],
  health: [
    "sport",
    "sporten",
    "training",
    "voetbal",
    "boksen",
    "sportschool",
    "gezondheid",
    "dokter",
    "tandarts",
    "slapen",
    "slaap",
    "wandelen",
    "eten",
    "water",
  ],
  social: [
    "afspreken",
    "afspraak",
    "vriend",
    "vriendin",
    "familie",
    "ouders",
    "collega",
    "team",
    "bellen met",
    "eten met",
    "verjaardag",
    "bezoek",
    "appje",
  ],
};

const domainRules = {
  school: ["school", "studie", "tentamen", "examen", "les", "college", "huiswerk", "scriptie", "stage"],
  werk: ["werk", "klant", "meeting", "deadline", "collega", "team", "factuur", "sollicitatie"],
  gezondheid: ["gezondheid", "sport", "slapen", "slaap", "dokter", "therapie", "eten", "wandelen", "energie"],
  administratie: ["belasting", "factuur", "verzekering", "administratie", "rekening", "betaal", "bank"],
  huis: ["huis", "kamer", "opruimen", "schoonmaken", "verhuizen", "verbouwing", "boodschappen"],
  relaties: ["vriend", "vriendin", "familie", "ouders", "partner", "collega", "afspraak", "verjaardag"],
  toekomstplannen: ["toekomst", "later", "doel", "droombaan", "opleiding", "verhuizen", "sparen", "plan"],
};

const urgentWords = ["vandaag", "morgen", "deadline", "urgent", "belangrijk", "eerst", "nu", "deze week", "inleveren"];
const calmFallback = "Gebruik Restructure een tijdje om inzichten te krijgen.";
const defaultSettings = {
  theme: "Donker",
  accent: "Teal",
  language: "Nederlands",
  notifications: false,
  reminderTiming: "Op tijdstip",
  quietNotifications: true,
  dndStart: "22:00",
  dndEnd: "08:00",
  weekStart: "Maandag",
  showVacations: true,
  showHolidays: true,
  time24: true,
  weekScroll: "Horizontaal",
  rememberAuto: true,
  rememberSchool: true,
  rememberWork: true,
  rememberSport: true,
  rememberFree: true,
  smartRemember: true,
  aiTone: "Rustig",
  aiHelp: "Normaal",
  dailyFocus: true,
  smallSteps: true,
  backup: false,
  storage: "Lokaal",
  animations: "Subtiel",
  compact: false,
  calmMode: false,
};
const accentPalettes = {
  Teal: { mint: "#47d8c8", glow: "71, 216, 200" },
  Blauw: { mint: "#8fb4e8", glow: "143, 180, 232" },
  Paars: { mint: "#c6b4e8", glow: "198, 180, 232" },
  Groen: { mint: "#8bd6a3", glow: "139, 214, 163" },
};

const dutchHolidays = [
  { title: "Nieuwjaarsdag", date: "2026-01-01", type: "holiday" },
  { title: "Goede Vrijdag", date: "2026-04-03", type: "holiday" },
  { title: "Eerste paasdag", date: "2026-04-05", type: "holiday" },
  { title: "Tweede paasdag", date: "2026-04-06", type: "holiday" },
  { title: "Koningsdag", date: "2026-04-27", type: "holiday" },
  { title: "Bevrijdingsdag", date: "2026-05-05", type: "holiday" },
  { title: "Hemelvaartsdag", date: "2026-05-14", type: "holiday" },
  { title: "Eerste pinksterdag", date: "2026-05-24", type: "holiday" },
  { title: "Tweede pinksterdag", date: "2026-05-25", type: "holiday" },
  { title: "Eerste kerstdag", date: "2026-12-25", type: "holiday" },
  { title: "Tweede kerstdag", date: "2026-12-26", type: "holiday" },
];

const schoolVacations = [
  { title: "Meivakantie", date: "2026-04-25", end: "2026-05-03", type: "vacation", meta: "Alle regio's" },
  { title: "Zomervakantie", date: "2026-07-04", end: "2026-08-16", type: "vacation", meta: "Regio Noord" },
  { title: "Zomervakantie", date: "2026-07-18", end: "2026-08-30", type: "vacation", meta: "Regio Midden" },
  { title: "Zomervakantie", date: "2026-07-11", end: "2026-08-23", type: "vacation", meta: "Regio Zuid" },
  { title: "Herfstvakantie", date: "2026-10-10", end: "2026-10-18", type: "vacation", meta: "Regio Noord" },
  { title: "Herfstvakantie", date: "2026-10-17", end: "2026-10-25", type: "vacation", meta: "Regio Midden en Zuid" },
  { title: "Kerstvakantie", date: "2026-12-19", end: "2027-01-03", type: "vacation", meta: "Alle regio's" },
  { title: "Voorjaarsvakantie", date: "2027-02-20", end: "2027-02-28", type: "vacation", meta: "Regio Noord en Midden" },
  { title: "Voorjaarsvakantie", date: "2027-02-13", end: "2027-02-21", type: "vacation", meta: "Regio Zuid" },
  { title: "Meivakantie", date: "2027-04-24", end: "2027-05-02", type: "vacation", meta: "Alle regio's" },
];

const defaults = {
  appointments: [],
  school: [],
  work: [],
  stuff: [],
  projects: [],
  tasks: [],
  goals: [],
  worries: [],
  ideas: [],
  routines: [],
  health: [],
  social: [],
  priorities: [],
  todayImportant: [],
  later: [],
};

const sampleData = {
  summary: "Gebruik Restructure een tijdje om inzichten te krijgen.",
  appointments: [],
  school: [],
  work: [],
  stuff: [],
  projects: [],
  tasks: [],
  goals: [],
  worries: [],
  ideas: [],
  routines: [],
  health: [],
  social: [],
  priorities: [],
  todayImportant: [],
  later: [],
};
const seededRememberItemIds = new Set(["school-sleutels", "schoolpas", "oplader", "laptop", "waterfles", "sportkleding"]);

const rememberLabels = {
  school: "School",
  werk: "Werk",
  sport: "Sport",
  "vrije tijd": "Vrije tijd",
};


